pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Construyendo aplicación..."
                sh 'docker build -t altctrlsupr/app:dev .'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                echo "Aplicando despliegue..."
                sh 'kubectl apply -f k8s/k8s.yaml'
            }
        }
    }
}
